name: Build & Test SISO OS

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Install dependencies
      run: sudo apt update && sudo apt install -y qemu-system-x86

    - name: Set up Rust target
      run: rustup target add x86_64-unknown-none

    - name: Build OS
      run: cargo build --target x86_64-unknown-none --verbose

    - name: Run OS in QEMU
      run: |
        qemu-system-x86_64 -drive format=raw,file=target/x86_64-unknown-none/debug/siso-os -nographic -no-reboot -monitor none -serial stdio
